const TodosTypes = {
  SET_TODOS: "SET_TODOS",
  UPDATE_TODOS: "UPDATE_TODOS",
  TOGGLE_TODO_COMPLETED: "TOGGLE_TODO_COMPLETED",
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
};

export default TodosTypes;
