const LocalStateTypes = {
  TOGGLE_MENU: "TOGGLE_MENU",
  CLOSE_MENU: "CLOSE_MENU",
  OPEN_ADD_TODO_MODAL: "OPEN_ADD_TODO_MODAL",
  CLOSE_ADD_TODO_MODAL: "CLOSE_ADD_TODO_MODAL",
  OPEN_ADD_PROJECT_MODAL: "OPEN_ADD_PROJECT_MODAL",
  CLOSE_ADD_PROJECT_MODAL: "CLOSE_ADD_PROJECT_MODAL",
  OPEN_ADD_LABEL_MODAL: "OPEN_ADD_LABEL_MODAL",
  CLOSE_ADD_LABEL_MODAL: "CLOSE_ADD_LABEL_MODAL",
  SET_INITIAL_DATA_LOADED: "SET_INITIAL_DATA_LOADED",
  SET_APP_DATA_ERRORS: "SET_APP_DATA_ERRORS",
};

export default LocalStateTypes;
