const LocalStateTypes = {
  TOGGLE_MENU: "TOGGLE_MENU",
  TOGGLE_MENU_IS_TRANSITIONING: "TOGGLE_MENU_IS_TRANSITIONING",
  CLOSE_MENU: "CLOSE_MENU",
  OPEN_ADD_TODO_MODAL: "OPEN_ADD_TODO_MODAL",
  CLOSE_ADD_TODO_MODAL: "CLOSE_ADD_TODO_MODAL",
  OPEN_ADD_PROJECT_MODAL: "OPEN_ADD_PROJECT_MODAL",
  CLOSE_ADD_PROJECT_MODAL: "CLOSE_ADD_PROJECT_MODAL",
  OPEN_ADD_LABEL_MODAL: "OPEN_ADD_LABEL_MODAL",
  CLOSE_ADD_LABEL_MODAL: "CLOSE_ADD_LABEL_MODAL",
};

export default LocalStateTypes;
